### ISSUE TITLE
Computation error in update interval

### ISSUE THREAD

**Issue by hcgraf** [unixorn/autoupdate-zgen#1]
Updates 7 times a day instead of every 7 days because of using / instead of \* (lines 44 and 45)…

**Comment by unixorn** [comment]
That's embarrassing. I thought I'd committed and pushed this months ago. That's what I get for working on the copy in ~/.zgen

Thanks for the catch, @hcgraf

**Comment by hcgraf** [comment]
Thanks for your quick response, and for your effort!

But I'm sorry, it won't work like this…
Because you're using the expr-utility, you either have to escape the multiplication sign using '_' or \_, or - better in my opinion - use zsh-builtins to do the computation, e.g. $((${day_seconds} \* ${ZGEN_PLUGIN_UPDATE_DAYS})).

**Comment by hcgraf** [comment]
oops, sorry, I didn't realize that you fixed that already…
Thanks a lot!
