### ISSUE TITLE
unknown condition: -gt

### ISSUE THREAD

**Issue by twnaing** [unixorn/autoupdate-zgen#13]
I am getting this error on startup of my ZSH shell (with zsh-quickstart-kit)

```zsh
expr: syntax error: missing argument after ‘-’
_zgen-check-for-updates:[:24: unknown condition: -gt
```

I traced it back to  `_zgen-check-for-updates` and haven't found anything on the internet to make it work.

it only happens with zsh 5.5 and not in zsh 5.4

**Comment by twnaing** [comment]
For the second line of error, I fixed by changing line 50 and 59 (from `[` and `]` to `[[` and `]]`).

I get the information from [this comment](https://github.com/zakaziko99/agnosterzak-ohmyzsh-theme/issues/8#issuecomment-299085571)

**Comment by twnaing** [comment]
For the first line of error, I found out that no content in `~/.zgen_plugin_lastupdate` file causing the issue.

fixed by running 

    echo $(date +%s) > ~/.zgen_plugin_lastupdate

**Comment by jnunderwood** [comment]
I also had to do the same thing for `~/.zgen_system_lastupdate`:

```shell
echo $(date +%s) > ~/.zgen_system_lastupdate
```

**Comment by unixorn** [comment]
I'll update the logic to create the file if it is missing. Thanks for the catch.

**Comment by Gy0m** [comment]
> Thank you idont have habits to read code that i k'wow nothing and thats. Mérité

**Comment by Gy0m** [comment]
I 've read some pages of git hub about zgen
